### ISSUE TITLE
Gender variable?

### ISSUE THREAD

**Issue by briatte** [rOpenGov/finpar#2]
Quick question – I'm looking at [these pages](http://www.eduskunta.fi/triphome/bin/hx3000.sh?{haku}=kaikki&LAJITNIMI=$) (MP biographies on the Finnish Parliament website), and I can't find a way to impute gender from the information provided.

I wrote some [rough imputation code](https://github.com/briatte/eduskunta/blob/master/data.r#L232-L235), based on first names and photos, but some first names might fit both males and females.

Needless to say, I don't speak Suomi. Is there an easy way to impute gender from first names? Did someone bother to do this for MPs from recent parliamentary sessions (35-36)?

I'm asking in relation to [this repo](https://github.com/briatte/eduskunta/), which builds legislative cosponsorship networks from the last two sessions of the Finnish Parliament.

Thanks in advance for any pointers!

**Comment by jlehtoma** [comment]
I just learned that there is a service called http://genderize.io/ that "determines the gender of a first name". E.g. 

http://api.genderize.io/?name=joona&language_id=fi
http://api.genderize.io/?name=leo&language_id=fi
http://api.genderize.io/?name=fran%C3%A7ois&language_id=fr

What's even better, rOpenSci has a R package [genderizeR](https://github.com/kalimu/genderizeR) for the API. Will need to test this on the list of current MPs.

**Comment by antagomir** [comment]
Super ! I was only aware of the "gender" R package.

**Comment by ouzor** [comment]
Great! I have other use for this as well.

**Comment by briatte** [comment]
This rocks!!

[Here's a test](https://gist.github.com/briatte/56158c25588a13a71b64) on 830 Finnish MPs. It seems to work really well. Problem solved.

Thanks again, this is a really great pick.

**Comment by jlehtoma** [comment]
Neat! Since this information is generally useful and thus far unavailable, I did a manual check on the names based on your [gist](https://gist.github.com/briatte/56158c25588a13a71b64). Following female names are categorically classified as male:

```
sisko
```

Following male names are categorically classified as male names:

```
assar
aulis
eeli
eino
jani
janne
kari
lauri
ola
pauli
viljami
```

Checked and corrected csv of Finnish MPs can be found in [`finpar/inst/extadat/mp_genders.csv`](https://github.com/rOpenGov/finpar/blob/master/inst/extdata/mp_genders.csv) (column `correct_gender`). Corrected names (as produced by `findGivenNames()` can be found in [`finpar/inst/extadat/name_genders.csv`](https://github.com/rOpenGov/finpar/blob/master/inst/extdata/name_genders.csv) (column `correct_gender`).

**Comment by antagomir** [comment]
I added the Finnish name-gender mappings derived from the Finnish population register (VRK) in the [fennica](https://github.com/rOpenGov/fennica) R package. This contains 11230 first names (according to VRK), with gender, gender probability, and name total counts. This may or may not be more comprehensive than genderizeR data for Finnish but the free genderizer API has a limit of 1000 queries a day so this might be helpful with instant analyses.

```
library(devtools)
install_github("ropengov/fennica")
library(fennica); 
tab <- get_gender_fi() 
```
